name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac-win:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: mac-installer
          path: dist/*.dmg
      - uses: actions/upload-artifact@v3
        with:
          name: win-installer
          path: dist/*.exe 